/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP1
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <LCD.h>
#include <startTimer_ISR.h>
#include <stopTimer_ISR.h>
#include <downPosition_PIN.h>
#include <downPosition_PIN_aliases.h>
#include <upPosition_PIN.h>
#include <upPosition_PIN_aliases.h>
#include <dbnc_CLK.h>
#include <sec_CNTR.h>
#include <readyTimer_ISR.h>
#include <min_CNTR.h>
#include <Timer.h>
#include <tenthSec_CNTR.h>
#include <timer_CLK.h>
#include <hr_CNTR.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/

